# Generated by Django 3.1.2 on 2020-11-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KasusProvinsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_provinsi', models.CharField(max_length=100)),
                ('data_json', models.JSONField()),
                ('update_terakhir', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KasusUpdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('spesimen', models.IntegerField()),
                ('spesimen_negatif', models.IntegerField()),
                ('kasus_terkonfirmasi_kum', models.IntegerField()),
                ('kasus_terkonfirmasi', models.IntegerField()),
                ('kasus_meninggal_kum', models.IntegerField()),
                ('kasus_meninggal', models.IntegerField()),
                ('kasus_sembuh_kum', models.IntegerField()),
                ('kasus_sembuh', models.IntegerField()),
                ('kasus_dirawat_kum', models.IntegerField()),
                ('kasus_dirawat', models.IntegerField()),
                ('kasus_suspek', models.IntegerField()),
                ('kab_kota_terdampak', models.SmallIntegerField()),
                ('transmisi_lokal', models.SmallIntegerField()),
                ('update_terakhir', models.DateTimeField()),
            ],
        ),
    ]
