# Generated by Django 3.1.2 on 2020-11-15 07:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('isi', ckeditor.fields.RichTextField()),
                ('Foto', models.TextField()),
                ('Sumber', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar', models.CharField(max_length=200)),
                ('nama', models.CharField(max_length=30)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidnews.news')),
            ],
        ),
    ]
